kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-pv-volume
  labels:
    type: local
    app: jenkins
spec:
  storageClassName: "oci"
  capacity:
    storage: 10Gi
  accessModes: [ "ReadWriteOnce" ]
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pv-claim
  labels:
    app: jenkins
spec:
  storageClassName: "oci"
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 10Gi


