apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    app: jenkins
spec:
  selector:
    app: jenkins
  type: LoadBalancer #Exposes the service as a node port
  ports:
  - port: 8080
    targetPort: 8080
